### ISSUE TITLE
Hide Packages & Releases

### ISSUE THREAD

**Issue by verma-kunal** [deepansharya1111/Keylogger-testing-phase#1]
Suggested to hide packages and releases if not being used in the project !!

![Screenshot 2021-07-04 at 2 47 29 PM](https://user-images.githubusercontent.com/72245772/124379811-c3bd3080-dcd6-11eb-9fc3-1ba15a9b9f00.png)

**Comment by deepansharya1111** [comment]
Thanks for letting me know, I had no idea that it can be done, I have fixed it.
